// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>> load(String fullPath, Locale locale ) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> en = {
  "Loading": "Loading",
  "Home": "Home",
  "US Markets": "US Markets",
  "Watchlist": "Watchlist",
  "Articles": "Articles",
  "Triple I": "Triple I",
  "Your Profile": "Your Profile",
  "Settings": "Settings",
  "Payments": "Payments",
  "Notifications": "Notifications",
  "Log Out": "Log Out",
  "Open": "Open",
  "Prev close": "Prev close",
  "Day High": "Day High",
  "Day Low": "Day Low",
  "52 WK High": "52 WK High",
  "52 WK Low": "52 WK Low",
  "Outstanding Shares": "Outstanding Shares",
  "Volume": "Volume",
  "Avg Vol": "Avg Vol",
  "MKT Cap": "MKT Cap",
  "P/E Ratio": "P/E Ratio",
  "EPS": "EPS",
  "Summary": "Summary",
  "CEO": "CEO",
  "Sector": "Sector",
  "Exchange": "Exchange",
  "About": "About",
  "No Articles Currently": "No Articles Currently",
  "Notification": "Notification",
  "Most Active": "Most Active",
  "Top Gainers": "Top Gainers",
  "Top Losers": "Top Losers",
  "Search a Stock...": "Search a Stock...",
  "Community": "Community",
  "Dow Jones": "Dow Jones",
  "NASDAQ": "NASDAQ",
  "News": "News",
  "Russell 2000": "Russell 2000",
  "S&P 500": "S & P 500",
  "Nasdaq": "Nasdaq",
  "Materials": "Materials",
  "Financials": "Financials",
  "Industrials": "Industrials",
  "Information Technology": "Information Technology",
  "Communication Services": "Communication Services",
  "Energy": "Energy",
  "Real Estate": "Real Estate",
  "Health Care": "Health Care",
  "Consumer Staples": "Consumer Staples",
  "Utilities": "Utilities",
  "Consumer Discretionary": "Consumer Discretionary",
  "Now": "Now",
  "1 D": "1 D",
  "5 D": "5 D",
  "1 M": "1 M",
  "1 Y": "1 Y",
  "10 Y": "10 Y",
  "No recent searches": "No recent searches",
  "Chart": "Chart",
  "Forum": "Forum"
};
static const Map<String,dynamic> he = {
  "Loading": "טוען",
  "Home": "בית",
  "US Markets": "שווקי ארה״ב",
  "Watchlist": "מועדפים",
  "Articles": "כתבות",
  "Triple I": "Triple I",
  "Your Profile": "הפרופיל שלי",
  "Settings": "הגדרות",
  "Payments": "תשלומים",
  "Notifications": "התראות",
  "Log Out": "התנתק",
  "Open": "פתיחה",
  "Prev close": "שער סגירה אחרון",
  "Day High": "גבוה יומי",
  "Day Low": "נמוך יומי",
  "52 WK High": "גבוה שנתי",
  "52 WK Low": "נמוך שנתי",
  "Outstanding Shares": "מניות מונפקות",
  "Volume": "ווליום - נפח מסחר",
  "Avg Vol": "ווליום ממוצע",
  "MKT Cap": "שווי שוק",
  "P/E Ratio": "מכפיל רווח",
  "EPS": "רווח למניה ",
  "Summary": "תמצות / סיכום תלוי ההקשר",
  "CEO": "מנכ\"ל",
  "Sector": "ענף",
  "Exchange": "בורסה",
  "About": "על אודות",
  "No Articles Currently": "אין כתבות כעת",
  "Notification": "התראות",
  "Most Active": "הכי פעילות",
  "Top Gainers": "הכי מרוויחות",
  "Top Losers": "הכי מפסידות",
  "Search a Stock...": "חפש מניה...",
  "Community": "קהילה",
  "Dow Jones": "דאו ג'ונס",
  "NASDAQ": "נאסד\"ק",
  "News": "חדשות",
  "Russell 2000": "ראסל 2000",
  "S&P 500": "S&P 500",
  "Nasdaq": "נאסד\"ק",
  "Materials": "סחורות",
  "Financials": "כספים",
  "Industrials": "תעשיות",
  "Information Technology": "טכנולוגיית מידע",
  "Communication Services": "שירותי תקשורת",
  "Energy": "אנרגיה",
  "Real Estate": "נדל\"ן",
  "Health Care": "בריאות",
  "Consumer Staples": "סיכות צרכנים",
  "Utilities": "כלי עזר",
  "Consumer Discretionary": "שיקול דעת צרכני",
  "Now": "עכשיו",
  "1 D": "יום",
  "5 D": "5 ימים",
  "1 M": "חודש",
  "1 Y": "שנה",
  "10 Y": "עשור",
  "No recent searches": "אין חיפושים אחרונים",
  "Chart": "גרף",
  "Forum": "פורום"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"en": en, "he": he};
}
